"""Regression tests for the global/static variable inventory.

Asserts that every shared-storage declaration kind appears in the inventory
regardless of risk status: globals (including no-risk constants), file
statics, function/block statics, header static instances, C++ static members
and supplemental/inactive declarations. Ordinary automatic locals, function
parameters and struct/union fields are explicitly excluded. Expected
declarations are written as fixtures, not generated by the same extractor.
"""
import json
from pathlib import Path
import tempfile
import unittest

from ecra.analysis import analyze, merge
from ecra.compilation import prepare
from ecra.config import load_config
from ecra.extract import Extractor
from ecra.html_report import write_html


ROOT = Path(__file__).resolve().parents[1]


class InventoryFixture(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory(prefix="ecra inventory test ")
        self.root = Path(self.tmp.name).resolve()
        self.addCleanup(self.tmp.cleanup)
        self.original_cwd = Path.cwd()
        self.addCleanup(lambda: __import__("os").chdir(self.original_cwd))
        (self.root / ".ecra").mkdir()

    def project(self, sources, contexts=None, **analysis):
        entries = []
        for name, text in sources.items():
            path = self.root / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            if name.endswith((".c", ".cpp")):
                entries.append(dict(directory=str(self.root), file=name,
                                    arguments=["arm-none-eabi-gcc", "-mcpu=cortex-m7", "-mthumb", "-c", name]))
        (self.root / "compile_commands.json").write_text(json.dumps(entries), encoding="utf-8")
        cfg = dict(version=1, analysis=dict(compile_database="compile_commands.json", **analysis),
                   contexts=contexts or [dict(id="isr", kind="ISR", functions=["ISR"]),
                                         dict(id="task", kind="TASK", functions=["Task"])],
                   review=dict(enabled=False))
        (self.root / ".ecra/semantics.yaml").write_text(json.dumps(cfg), encoding="utf-8")
        return load_config(self.root)[0]

    def extract(self, cfg):
        units, audit = prepare(self.root, cfg)
        parts = [Extractor(dict(root=str(self.root), unit=u, config=cfg)).run() for u in units]
        for part in parts:
            self.assertEqual(part["parse_status"], "PARSED", part.get("diagnostics"))
        facts = merge(parts)
        coverage = dict(translation_units_failed=0, **audit)
        report = analyze(facts, cfg, coverage)
        return facts, report

    def names_by_kind(self, facts):
        result = {}
        for v in facts["variables"]:
            result.setdefault(v["kind"], []).append(v["name"])
        return result


class TestLocalsAndParameters(InventoryFixture):
    def test_ordinary_locals_are_excluded(self):
        """Automatic locals are per-invocation storage, not shared objects."""
        cfg = self.project({"a.c": """
            int g;
            void ISR(void) { g++; }
            void Task(void) {
                int local_a = 1;
                int local_b = 2;
                g = local_a + local_b;
            }
        """})
        facts, report = self.extract(cfg)
        kinds = self.names_by_kind(facts)
        self.assertNotIn("LOCAL", kinds)
        self.assertFalse(any(v["name"] in {"local_a", "local_b"} for v in facts["variables"]))
        self.assertFalse(any(f.get("symbol_id", "").startswith("auto::") for f in report["findings"]))

    def test_named_parameters_are_excluded(self):
        """Function parameters are not independent shared objects."""
        cfg = self.project({"a.c": """
            int g;
            void Process(int count, char *buffer, const unsigned flags) {
                g += count;
            }
            void ISR(void) { g++; }
            void Task(void) { Process(1, 0, 0); }
        """})
        facts, report = self.extract(cfg)
        kinds = self.names_by_kind(facts)
        self.assertNotIn("PARAMETER", kinds)
        self.assertFalse(any(v["name"] in {"count", "buffer", "flags"} for v in facts["variables"]))
        self.assertFalse(any(f.get("symbol_id", "").startswith("parm::") for f in report["findings"]))

    def test_shadowed_function_statics_get_distinct_ids(self):
        """Nested-scope function statics with the same name must have distinct IDs."""
        cfg = self.project({"a.c": """
            int g;
            void Task(void) {
                static int x = 1;
                { static int x = 2; g = x; }
                g += x;
            }
            void ISR(void) { g++; }
        """})
        facts, _ = self.extract(cfg)
        xs = [v for v in facts["variables"] if v["name"] == "x" and v["kind"] == "LOCAL_STATIC"]
        self.assertEqual(len(xs), 2)
        self.assertNotEqual(xs[0]["symbol_id"], xs[1]["symbol_id"])

    def test_array_and_pointer_function_statics(self):
        """Array and pointer function statics must be correctly typed in inventory."""
        cfg = self.project({"a.c": """
            int g;
            void Task(void) {
                static int arr[8];
                static int *ptr = &g;
                arr[0] = *ptr;
            }
            void ISR(void) { g++; }
        """})
        facts, _ = self.extract(cfg)
        arr = next(v for v in facts["variables"] if v["name"] == "arr" and v["kind"] == "LOCAL_STATIC")
        ptr = next(v for v in facts["variables"] if v["name"] == "ptr" and v["kind"] == "LOCAL_STATIC")
        self.assertTrue(arr["is_array"])
        self.assertTrue(ptr["is_pointer"])

    def test_locals_do_not_break_pointer_alias_solving(self):
        """Automatic locals must still drive pointer/alias/snapshot analysis of shared objects."""
        cfg = self.project({"a.c": """
            int g, h;
            void ISR(void) { g++; }
            void Task(void) {
                int *p = &g;
                *p = 5;
                int snapshot = h;
                h = snapshot + 1;
            }
        """})
        facts, report = self.extract(cfg)
        g_var = next(v for v in facts["variables"] if v["name"] == "g")
        self.assertTrue(any(a.get("via_alias") == "p" and a["access_kind"] == "WRITE" for a in g_var["accesses"]))


class TestNoRiskAndUnusedSymbols(InventoryFixture):
    def test_no_risk_unused_symbol_remains_in_inventory(self):
        """A variable with no access evidence must still appear in inventory."""
        cfg = self.project({"a.c": """
            static int never_used;
            int g;
            void ISR(void) { g++; }
            void Task(void) { g++; }
        """})
        facts, report = self.extract(cfg)
        self.assertTrue(any(v["name"] == "never_used" for v in facts["variables"]))
        unused = next(v for v in facts["variables"] if v["name"] == "never_used")
        self.assertEqual(unused['screening_reason'], 'SAFE_NO_RUNTIME_ACCESS')
        self.assertFalse(any(f.get('symbol_id') == unused['symbol_id'] for f in report['findings']))

    def test_const_no_risk_symbol_in_inventory(self):
        """A const variable with no risk must appear in inventory."""
        cfg = self.project({"a.c": """
            const int table[3] = {1, 2, 3};
            int g;
            void ISR(void) { g++; }
            void Task(void) { g++; }
        """})
        facts, report = self.extract(cfg)
        self.assertTrue(any(v["name"] == "table" and v["is_const"] for v in facts["variables"]))
        table = next(v for v in facts["variables"] if v["name"] == "table")
        self.assertEqual(table["audit_status"], "SCREENED_NO_CONCURRENCY_RISK")


class TestStaticIdentity(InventoryFixture):
    def test_same_name_file_statics_keep_distinct_ids(self):
        """Two file statics named 'state' in different TUs must have distinct IDs."""
        cfg = self.project({
            "a.c": "static int state; void ISR(void){state++;}",
            "b.c": "static int state; void Task(void){state++;}"})
        facts, _ = self.extract(cfg)
        states = [v for v in facts["variables"] if v["name"] == "state" and v["kind"] == "FILE_STATIC"]
        self.assertEqual(len(states), 2)
        self.assertNotEqual(states[0]["symbol_id"], states[1]["symbol_id"])
        self.assertNotEqual(states[0]["definition_file"], states[1]["definition_file"])

    def test_header_static_per_tu_identity(self):
        """Header statics must produce one instance per TU."""
        cfg = self.project({
            "h.h": "static int hs;",
            "a.c": '#include "h.h"\nint g; void ISR(void){hs++;g++;}',
            "b.c": '#include "h.h"\nvoid Task(void){hs++;}'})
        facts, _ = self.extract(cfg)
        hss = [v for v in facts["variables"] if v["name"] == "hs" and v["kind"] == "FILE_STATIC"]
        self.assertEqual(len(hss), 2)


class TestHeaderDefinitionsAndExtern(InventoryFixture):
    def test_extern_declaration_and_definition_merged(self):
        """extern declaration in header and definition in .c must merge to one variable."""
        cfg = self.project({
            "h.h": "extern int shared;",
            "a.c": '#include "h.h"\nint shared;\nvoid ISR(void){shared++;}',
            "b.c": '#include "h.h"\nvoid Task(void){shared++;}'})
        facts, _ = self.extract(cfg)
        shareds = [v for v in facts["variables"] if v["name"] == "shared"]
        self.assertEqual(len(shareds), 1)
        self.assertEqual(len(shareds[0]["declarations"]), 2)

    def test_block_scope_extern_is_a_global_declaration(self):
        """A block-scope extern declares shared storage, not an automatic local."""
        cfg = self.project({"a.c": """
            int shared;
            void Task(void) { extern int shared; shared++; }
            void ISR(void) { shared++; }
        """})
        facts, _ = self.extract(cfg)
        shareds = [v for v in facts["variables"] if v["name"] == "shared"]
        self.assertEqual(len(shareds), 1)
        self.assertIn(shareds[0]["kind"], {"GLOBAL", "FILE_STATIC"})


class TestUncompiledAndSupplemental(InventoryFixture):
    def test_uncompiled_selected_source_supplemental_inventory(self):
        """A source file in scope but not in compile DB must get supplemental parsing."""
        (self.root / "a.c").write_text("int g; void ISR(void){g++;} void Task(void){g++;}", encoding="utf-8")
        (self.root / "extra.c").write_text("static int extra_var; void Extra(void){extra_var++;}", encoding="utf-8")
        (self.root / "compile_commands.json").write_text(json.dumps([
            dict(directory=str(self.root), file="a.c",
                 arguments=["arm-none-eabi-gcc", "-mcpu=cortex-m7", "-mthumb", "-c", "a.c"])
        ]), encoding="utf-8")
        cfg = dict(version=1, analysis=dict(compile_database="compile_commands.json"),
                   contexts=[dict(id="isr", kind="ISR", functions=["ISR"]),
                             dict(id="task", kind="TASK", functions=["Task"])],
                   review=dict(enabled=False))
        (self.root / ".ecra/semantics.yaml").write_text(json.dumps(cfg), encoding="utf-8")
        from ecra.cli import run
        code = run(self.root, no_review=True)
        self.assertEqual(code, 2)
        facts = json.loads((self.root / ".ecra/facts.json").read_text(encoding="utf-8"))
        self.assertTrue(any(v["name"] == "extra_var" for v in facts["variables"]))
        extra_var = next(v for v in facts["variables"] if v["name"] == "extra_var")
        self.assertEqual(extra_var.get("coverage_source"), "supplemental")

    def test_unused_header_gets_supplemental_inventory(self):
        """A header not included by any TU must be supplementally parsed."""
        (self.root / "a.c").write_text("int g; void ISR(void){g++;} void Task(void){g++;}", encoding="utf-8")
        (self.root / "orphan.h").write_text("static int hidden;\nextern int also_hidden;", encoding="utf-8")
        (self.root / "compile_commands.json").write_text(json.dumps([
            dict(directory=str(self.root), file="a.c",
                 arguments=["arm-none-eabi-gcc", "-mcpu=cortex-m7", "-mthumb", "-c", "a.c"])
        ]), encoding="utf-8")
        cfg = dict(version=1, analysis=dict(compile_database="compile_commands.json"),
                   contexts=[dict(id="isr", kind="ISR", functions=["ISR"]),
                             dict(id="task", kind="TASK", functions=["Task"])],
                   review=dict(enabled=False))
        (self.root / ".ecra/semantics.yaml").write_text(json.dumps(cfg), encoding="utf-8")
        from ecra.cli import run
        run(self.root, no_review=True)
        report = json.loads((self.root / ".ecra/reports/global_static_concurrency.json").read_text(encoding="utf-8"))
        self.assertIn("orphan.h", report["coverage"].get("unlisted_headers", []))
        facts = json.loads((self.root / ".ecra/facts.json").read_text(encoding="utf-8"))
        hidden = [v for v in facts["variables"] if v["name"] == "hidden"]
        self.assertTrue(hidden)
        self.assertEqual(hidden[0].get("coverage_source"), "supplemental")

    def test_parse_failure_shows_partial_inventory_and_gaps(self):
        """A parse failure must show remaining variables and the failure reason."""
        (self.root / "a.c").write_text("int g; void ISR(void){g++;} void Task(void){g++;}", encoding="utf-8")
        (self.root / "bad.c").write_text('#include "nonexistent.h"\nint broken;', encoding="utf-8")
        (self.root / "compile_commands.json").write_text(json.dumps([
            dict(directory=str(self.root), file=name,
                 arguments=["arm-none-eabi-gcc", "-mcpu=cortex-m7", "-mthumb", "-c", name])
            for name in ("a.c", "bad.c")
        ]), encoding="utf-8")
        cfg = dict(version=1, analysis=dict(compile_database="compile_commands.json"),
                   contexts=[dict(id="isr", kind="ISR", functions=["ISR"]),
                             dict(id="task", kind="TASK", functions=["Task"])],
                   review=dict(enabled=False))
        (self.root / ".ecra/semantics.yaml").write_text(json.dumps(cfg), encoding="utf-8")
        from ecra.cli import run
        code = run(self.root, no_review=True)
        self.assertEqual(code, 2)
        report = json.loads((self.root / ".ecra/reports/global_static_concurrency.json").read_text(encoding="utf-8"))
        self.assertEqual(report["analysis_status"], "INCOMPLETE")
        self.assertTrue(report["coverage"]["translation_units_failed"] >= 1)
        facts = json.loads((self.root / ".ecra/facts.json").read_text(encoding="utf-8"))
        self.assertTrue(any(v["name"] == "g" for v in facts["variables"]))


class TestExcludedFilesAndMacros(InventoryFixture):
    def test_excluded_files_do_not_leak_variables(self):
        """Excluded file variables must not appear in inventory or findings."""
        cfg = self.project({
            "App/main.c": "int own; int main(void){return own;}",
            "Vendor/lib.c": "int vendor_private;",
        }, include_dirs=["App"], exclude_dirs=["Vendor"])
        facts, report = self.extract(cfg)
        self.assertFalse(any(v["name"] == "vendor_private" for v in facts["variables"]))
        self.assertTrue(any(v["name"] == "own" for v in facts["variables"]))
        self.assertEqual(report["coverage"]["audit_scope"]["variables_omitted"], 1)

    def test_macro_declared_variable_in_inventory(self):
        """A variable declared via macro expansion must appear in inventory."""
        cfg = self.project({"a.c": """
            #define DECLARE_GLOBAL(name) int name
            DECLARE_GLOBAL(g_macro);
            int g;
            void ISR(void) { g++; }
            void Task(void) { g_macro++; g++; }
        """})
        facts, _ = self.extract(cfg)
        self.assertTrue(any(v["name"] == "g_macro" for v in facts["variables"]))


class TestExistingRiskEvidence(InventoryFixture):
    def test_existing_risk_findings_preserved(self):
        """Existing concurrency findings must not be suppressed by new inventory."""
        cfg = self.project({"a.c": """
            int g;
            void ISR(void) { g++; }
            void Task(void) { g++; }
        """})
        facts, report = self.extract(cfg)
        g = next(v for v in facts["variables"] if v["name"] == "g")
        finding = next(f for f in report["findings"] if f.get("symbol_id") == g["symbol_id"])
        self.assertIn("GS-MULTI-CONTEXT", finding["rules"])
        self.assertIn("GS-MULTI-WRITER", finding["rules"])

    def test_pointer_and_address_evidence_preserved(self):
        """Pointer alias and address-take evidence must survive inventory expansion."""
        cfg = self.project({"a.c": """
            int g, arr[8]; int *gp = &g;
            void ISR(void) { g++; }
            void Task(void) { int *p = &g; *p = 5; gp = arr; gp[0] = 1; }
        """})
        facts, report = self.extract(cfg)
        g = next(v for v in facts["variables"] if v["name"] == "g")
        self.assertTrue(any(a.get("via_alias") == "p" for a in g["accesses"]))
        arr = next(v for v in facts["variables"] if v["name"] == "arr")
        self.assertTrue(any(a["access_kind"] == "ADDRESS_TAKEN" for a in arr["accesses"]))


class TestHTMLInventoryDefaults(InventoryFixture):
    def test_inventory_is_default_panel_and_excludes_automatic_storage(self):
        """index.html must default to the inventory panel and show only globals/statics."""
        cfg = self.project({"a.c": """
            int g_msgSP;
            static int state;
            void ISR(void) { g_msgSP = 1; state++; }
            void Task(void *arg) { int local = g_msgSP; g_msgSP = 2; (void)arg; }
        """})
        facts, report = self.extract(cfg)
        out = self.root / ".ecra"
        out.mkdir(exist_ok=True)
        write_html(out, facts, report, [])
        html_text = (out / "index.html").read_text(encoding="utf-8")
        self.assertIn("g_msgSP", html_text)
        self.assertIn("state", html_text)
        self.assertNotIn("local_inventory", html_text)
        self.assertNotIn("局部变量 / 参数 / 字段", html_text)
        self.assertNotIn('value="local"', html_text)
        self.assertFalse(any(v["name"] == "local" for v in facts["variables"]))
        self.assertIn('let active=document.getElementById', html_text)
        from ecra.html_report import DECISIONS
        for key in DECISIONS:
            self.assertIn(key, html_text)

    def test_html_shows_g_msgSP_and_both_state_records(self):
        """Specifically verify g_msgSP and both state records in HTML."""
        cfg = self.project({
            "h.h": "extern int g_msgSP; static int state;",
            "a.c": '#include "h.h"\nint g_msgSP;\nvoid ISR(void){g_msgSP=1;state++;}',
            "b.c": '#include "h.h"\nvoid Task(void){g_msgSP=2;state++;}'})
        facts, report = self.extract(cfg)
        out = self.root / ".ecra"
        out.mkdir(exist_ok=True)
        write_html(out, facts, report, [])
        html_text = (out / "index.html").read_text(encoding="utf-8")
        self.assertIn("g_msgSP", html_text)
        states = [v for v in facts["variables"] if v["name"] == "state"]
        self.assertEqual(len(states), 2)
        for s in states:
            self.assertIn(s["symbol_id"], html_text)

    def test_coverage_by_kind_in_report(self):
        """Coverage must include inventory_by_kind counts for globals/statics only."""
        cfg = self.project({"a.c": """
            int g; static int s;
            void ISR(void) { g++; s++; }
            void Task(void) { int local = 0; g = local; }
        """})
        facts, report = self.extract(cfg)
        self.assertIn("inventory_by_kind", report["coverage"])
        kinds = report["coverage"]["inventory_by_kind"]
        self.assertIn("GLOBAL", kinds)
        self.assertIn("FILE_STATIC", kinds)
        self.assertNotIn("LOCAL", kinds)
        self.assertNotIn("PARAMETER", kinds)
        self.assertNotIn("FIELD", kinds)


class TestEngineChangeInvalidation(InventoryFixture):
    def test_old_engine_scan_cannot_be_refreshed(self):
        """A cached scan from a different engine must be rerun, not refreshed."""
        from unittest.mock import patch
        from ecra.cli import run
        from ecra.workflow import saved_run
        self.project({"a.c": "int g; void ISR(void){g++;} void Task(void){g++;}"})
        self.assertEqual(run(self.root, no_review=True), 2)
        with patch('ecra.workflow.engine_digest', return_value='stale-engine-digest'):
            with self.assertRaisesRegex(ValueError, '分析实现或分析配置已变化'):
                saved_run(self.root, render_only=True)
        # The matching engine still allows an ordinary report refresh.
        self.assertIn(saved_run(self.root, render_only=True), (1, 2))

    def test_old_engine_scan_cannot_be_reviewed(self):
        """A cached scan from a different engine must be rerun, not reviewed."""
        from unittest.mock import patch
        from ecra.cli import run
        from ecra.workflow import saved_run
        self.project({"a.c": "int g; void ISR(void){g++;} void Task(void){g++;}"})
        self.assertEqual(run(self.root, no_review=True), 2)
        with patch('ecra.workflow.engine_digest', return_value='stale-engine-digest'):
            with self.assertRaisesRegex(ValueError, '分析实现或分析配置已变化'):
                saved_run(self.root)
        self.assertFalse((self.root / '.ecra/scan.lock').exists())


if __name__ == "__main__":
    unittest.main()
